---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  namespace: db
spec:
  restartPolicy: Never

  containers:
    - name: mysql-client
      image: mysql:8.0
      command:
        - sleep
      args:
        - infinity

      stdin: true
      tty: true
